# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Clean build directory"
  lane :clean do
    gradle(task: "clean")
  end

  desc "Ktlint"
  lane :ktlint do
    gradle(
      task: "ktlintCheck"
    )
  end

  desc "Lint"
  lane :lint do
    gradle(
      task: "lint"
    )
  end

  desc "Test"
  lane :test do
    gradle(
      task: "test"
    )
  end

  desc "Assemble"
  lane :assemble do
    gradle(
      task: "assemble",
      build_type: "Debug"
    )
  end

  desc "Bundle"
  lane :bundle do
   gradle(
     task: "bundle",
     flavor: "GooglePlay",
     build_type: "Release"
   )
  end

  desc "Upload"
  lane :upload do
    upload_to_play_store(
      track: "internal"
    )
  end

  desc "Test and build"
  lane :build do
    clean
    ktlint
    lint
    test
    assemble
  end

  desc "Test and release"
  lane :playstore do
    clean
    ktlint
    lint
    test
    bundle
    upload
  end
end
